#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xB9069B1335700CDC (infra-root@openstack.org)
#
Name     : python-manilaclient
Version  : 1.14.0
Release  : 18
URL      : http://tarballs.openstack.org/python-manilaclient/python-manilaclient-1.14.0.tar.gz
Source0  : http://tarballs.openstack.org/python-manilaclient/python-manilaclient-1.14.0.tar.gz
Source99 : http://tarballs.openstack.org/python-manilaclient/python-manilaclient-1.14.0.tar.gz.asc
Summary  : Client library for OpenStack Manila API.
Group    : Development/Tools
License  : Apache-2.0
Requires: python-manilaclient-bin
Requires: python-manilaclient-python
Requires: Babel
Requires: oslo.config
Requires: oslo.log
Requires: oslo.serialization
Requires: oslo.utils
Requires: pbr
Requires: python-keystoneclient
Requires: requests
Requires: simplejson
Requires: six
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
========================
Team and repository tags
========================
.. image:: http://governance.openstack.org/badges/python-manilaclient.svg
:target: http://governance.openstack.org/reference/tags/index.html

%package bin
Summary: bin components for the python-manilaclient package.
Group: Binaries

%description bin
bin components for the python-manilaclient package.


%package python
Summary: python components for the python-manilaclient package.
Group: Default

%description python
python components for the python-manilaclient package.


%prep
%setup -q -n python-manilaclient-1.14.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489785926
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1489785926
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/manila

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
